=== marcospdsf/EOT/data/conf/shops.xsd
<?xml version="1.0"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="stendhal"
	xmlns:tns="http://www.example.org/shops" elementFormDefault="qualified"
	xmlns:Q2="stendhal">

	<element name="shops" type="Q2:ShopGroup" />

	<complexType name="ShopGroup">
		<sequence>
			<element name="shop" type="Q2:Shop" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="Shop">
		<sequence>
			<element name="item" type="Q2:ShopItem" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
		<attribute name="name" type="string" use="required" />
		<attribute name="type" type="Q2:ShopType" use="required" />
		<attribute name="condition" type="string" use="optional" />
	</complexType>

	<simpleType name="ShopType">
		<restriction base="string">
			<enumeration value="buys" />
			<enumeration value="sells" />
		</restriction>
	</simpleType>

	<complexType name="ShopItem">
		<attribute name="name" type="string" use="required" />
		<attribute name="price" type="int" use="required" />
	</complexType>

</schema>

=== marcospdsf/EOT/data/conf/shops.xml
<?xml version="1.0" encoding="UTF-8"?>

<shops xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal shops.xsd">

	<shop name="food&amp;drinks" type="sells">
		<item name="beer" price="10" />
		<item name="wine" price="15" />
		<item name="flask" price="5" />
		<item name="cheese" price="20" />
		<item name="apple" price="10" />
		<item name="carrot" price="10" />
		<item name="meat" price="40" />
		<item name="ham" price="80" />
	</shop>

	<shop name="adosfoodseller" type="sells">
		<item name="apple" price="50" />
		<item name="carrot" price="50" />
		<item name="olive oil" price="135" />
		<item name="vinegar" price="135" />
	</shop>

	<shop name="buyfood" type="buys">
		<item name="cheese" price="5" />
		<item name="meat" price="10" />
		<item name="spinach" price="15" />
		<item name="ham" price="20" />
		<item name="flour" price="25" />
		<item name="porcini" price="30" />
	</shop>

	<shop name="healing" type="sells">
		<item name="antidote" price="50" />
		<item name="minor potion" price="100" />
		<item name="potion" price="250" />
		<item name="greater potion" price="500" />
	</shop>

	<shop name="superhealing" type="sells">
		<item name="antidote" price="50" />
		<item name="greater antidote" price="100" />
		<item name="potion" price="250" />
		<item name="greater potion" price="500" />
		<item name="mega potion" price="1500" />
	</shop>

	<shop name="scrolls" type="sells">
		<item name="home scroll" price="250" />
		<item name="summon scroll" price="200" />
		<item name="empty scroll" price="2000" />
	</shop>

	<shop name="fadoscrolls" type="sells">
		<item name="fado city scroll" price="600" />
		<item name="empty scroll" price="2200" />
	</shop>

	<shop name="nalworscrolls" type="sells">
		<item name="nalwor city scroll" price="400" />
		<item name="empty scroll" price="2000" />
	</shop>

	<shop name="adosscrolls" type="sells">
		<item name="ados city scroll" price="400" />
		<item name="empty scroll" price="2000" />
	</shop>

	<shop name="kirdnehscrolls" type="sells">
		<item name="kirdneh city scroll" price="400" />
		<item name="home scroll" price="400" />
		<item name="empty scroll" price="2000" />
	</shop>

	<shop name="allscrolls" type="sells">
		<item name="home scroll" price="250" />
		<item name="summon scroll" price="200" />
		<item name="empty scroll" price="2000" />
		<item name="ados city scroll" price="400" />
		<item name="nalwor city scroll" price="400" />
		<item name="fado city scroll" price="600" />
		<item name="kirdneh city scroll" price="600" />
		<item name="deniran city scroll" price="800" />
	</shop>

	<shop name="sellstuff" type="sells">
		<item name="knife" price="15" />
		<item name="club" price="10" />
		<item name="dagger" price="25" />
		<item name="wooden shield" price="25" />
		<item name="dress" price="25" />
		<item name="leather helmet" price="25" />
		<item name="cloak" price="30" />
		<item name="leather legs" price="35" />
	</shop>

	<shop name="sellbetterstuff1" type="sells">
		<item name="blue armor" price="14000" />
		<item name="blue boots" price="3000" />
		<item name="blue striped cloak" price="5000" />
		<item name="blue helmet" price="6000" />
		<item name="blue legs" price="6000" />
		<item name="blue shield" price="20000" />
		<item name="assassin dagger" price="12000" />
	</shop>

	<shop name="sellbetterstuff2" type="sells">
		<item name="shadow armor" price="18000" />
		<item name="shadow boots" price="4000" />
		<item name="shadow cloak" price="7000" />
		<item name="shadow helmet" price="8000" />
		<item name="shadow legs" price="10000" />
		<item name="shadow shield" price="30000" />
		<item name="hell dagger" price="20000" />
	</shop>

	<shop name="sellrangedstuff" type="sells">
		<item name="wooden bow" price="300" />
		<item name="wooden arrow" price="2" />
	</shop>

	<shop name="buystuff" type="buys">
		<item name="short sword" price="15" />
		<item name="sword" price="60" />
		<item name="studded shield" price="20" />
		<item name="studded armor" price="22" />
		<item name="studded helmet" price="17" />
		<item name="studded legs" price="20" />
		<item name="chain armor" price="29" />
		<item name="chain helmet" price="25" />
		<item name="chain legs" price="27" />
	</shop>

	<shop name="selltools" type="sells">
		<item name="small axe" price="15" />
		<item name="hand axe" price="25" />
		<item name="axe" price="40" />
		<!-- enable these if you need them for a quest or something -->
		<!-- <item name="pick" price="50" /> -->
		<!-- <item name="shovel" price="50" /> -->
		<item name="hammer" price="60" />
		<item name="old scythe" price="120" /> <!-- used for harvest grain. -->
		<item name="sickle" price="80" /> <!-- for harvesting cane fields -->
		<item name="gold pan" price="230" />
	</shop>

	<shop name="buyiron" type="buys">
		<item name="iron" price="75" />
	</shop>

	<shop name="buygrain" type="buys">
		<item name="grain" price="1" />
	</shop>

	<shop name="sellrings" type="sells">
		<item name="engagement ring" price="5000" />
	</shop>

	<!-- gold and gemstones -->
	<shop name="buyprecious" type="buys">
		<item name="gold bar" price="250" />
		<item name="emerald" price="200" />
		<item name="sapphire" price="400" />
		<item name="carbuncle" price="600" />
		<item name="diamond" price="800" />
		<item name="obsidian" price="1000" />
		<item name="mithril bar" price="2500" />
	</shop>

	<shop name="buyrare" type="buys">
		<!-- rare weapons -->
		<item name="scimitar" price="65" />
		<item name="katana" price="70" />
		<item name="bardiche" price="75" />
		<item name="golden hammer" price="80" />
		<!-- rare armor -->
		<item name="enhanced chainmail" price="32" />
		<item name="golden chainmail" price="52" />
		<item name="plate armor" price="62" />
		<item name="plate shield" price="40" />
		<item name="lion shield" price="50" />
		<item name="blue legs" price="500" />
	</shop>

	<!-- rare elf weapons buyer -->
	<shop name="elfbuyrare" type="buys">
		<item name="battle axe" price="70" />
		<item name="twoside axe" price="80" />
		<item name="claymore" price="90" />
		<item name="broadsword" price="100" />
		<item name="staff" price="75" />
		<item name="enhanced lion shield" price="100" />
		<item name="crown shield" price="120" />
	</shop>

	<!-- more rare weapons shop (fado) -->
	<shop name="buyrare2" type="buys">
		<item name="war hammer" price="120" />
		<item name="biting sword" price="150" />
		<item name="crossbow" price="175" />
		<item name="great sword" price="250" />
		<item name="fire sword" price="2000" />
		<item name="ice sword" price="5000" />
		<item name="hell dagger" price="8000" />
	</shop>

	<!-- very rare armor shop (ados) -->
	<shop name="buyrare3" type="buys">
		<item name="golden legs" price="3000" />
		<item name="shadow legs" price="5000" />
		<item name="golden armor" price="7000" />
		<item name="shadow armor" price="9000" />
		<item name="golden shield" price="10000" />
		<item name="shadow shield" price="15000" />
	</shop>

	<!-- less rare armor shop (kobold city - kobolds drop some of these things) -->
	<shop name="buystuff2" type="buys">
		<item name="leather scale armor" price="65" />
		<item name="studded legs" price="70" />
		<item name="studded boots" price="75" />
		<item name="chain boots" price="100" />
		<item name="skull shield" price="100" />
		<item name="unicorn shield" price="125" />
		<item name="viking helmet" price="250" />
	</shop>

	<shop name="sellstuff2" type="sells">
		<item name="leather boots" price="50" />
		<item name="studded helmet" price="60" />
		<item name="studded shield" price="80" />
		<item name="sword" price="90" />
		<item name="dwarf cloak" price="230" />
	</shop>

	<!-- cloaks shop -->
	<shop name="buycloaks" type="buys">
		<item name="blue elf cloak" price="300" />
		<item name="green dragon cloak" price="400" />
		<item name="blue dragon cloak" price="2000" />
		<item name="shadow cloak" price="3000" />
		<item name="black dragon cloak" price="4000" />
		<item name="golden cloak" price="5000" />
		<item name="chaos cloak" price="10000" />
		<item name="black cloak" price="20000" />
	</shop>

	<shop name="boots&amp;helm" type="buys">
		<!--
			boots (mithrilbourgh)
			Note the shop sign is done by hand in
			games.stendhal.server.maps.mithrilbourgh.stores
			Because I wanted to split boots and helmets
			Please if you change anything, change also the sign (by hand)
		-->
		<item name="steel boots" price="1000" />
		<item name="golden boots" price="1500" />
		<item name="shadow boots" price="2000" />
		<item name="stone boots" price="2500" />
		<item name="chaos boots" price="4000" />
		<item name="green thing boots" price="6000" />
		<item name="xeno boots" price="8000" />
		<!--
			helmet (mithrilbourgh)
			Note the shop sign is done by hand in
			games.stendhal.server.maps.mithrilbourgh.stores
		-->
		<item name="golden helmet" price="3000" />
		<item name="shadow helmet" price="4000" />
		<item name="horned golden helmet" price="5000" />
		<item name="chaos helmet" price="6000" />
		<item name="magic chain helmet" price="8000" />
		<item name="xeno helmet" price="8000" />
		<item name="black helmet" price="10000" />
	</shop>

	<!-- buy axes (woodcutter) -->
	<shop name="buyaxe" type="buys">
		<item name="halberd" price="2000" />
		<item name="golden twoside axe" price="4000" />
		<item name="magic twoside axe" price="6000" />
		<item name="durin axe" price="8000" />
		<item name="black scythe" price="9000" />
		<item name="chaos axe" price="10000" />
		<item name="black halberd" price="12000" />
	</shop>

	<!-- buy chaos items (scared dwarf, after quest) -->
	<shop name="buychaos" type="buys">
		<item name="chaos legs" price="8000" />
		<item name="chaos sword" price="12000" />
		<item name="chaos shield" price="18000" />
		<item name="chaos armor" price="20000" />
	</shop>

	<!-- buy elvish items (albino elf, after quest) -->
	<shop name="buyelvish" type="buys">
		<item name="elvish boots" price="300" />
